Use conda-pack to simplify Dockerfile
triton-inference-server/fil_backend pull request #222
Opened 2022-04-01 17:09 UTC by wphicks

Use conda-pack to move conda environments from dedicated conda installation layers to condaless layers where they will be used. Reduce unnecessary cache invalidation for conda installation layers.

2022-04-01 18:32 UTC, wphicks commented on ci/gitlab/build.sh
> +  bash -c 'source /conda/test/bin/activate && /qa/generate_example_models.sh'
Which bit? `conda-pack` itself? Latest commit was 10 days ago, so I'm assuming not?

2022-04-01 18:34 UTC, divyegala commented on ci/gitlab/build.sh
> +  bash -c 'source /conda/test/bin/activate && /qa/generate_example_models.sh'
Activating a conda environment with `source`. But it seems like we are running the script of `activate` itself, which should be okay. I'll defer the actual review to someone with more experience for this PR

2022-04-01 21:20 UTC, wphicks commented on ci/gitlab/build.sh
> +  bash -c 'source /conda/test/bin/activate && /qa/generate_example_models.sh'
Ah, I understand what you're saying! That's not the usual `conda` activation but the activation script for the `conda-pack`ed environment. That's the usual method for activating such environments.

2022-04-04 18:55 UTC, dantegd commented on ci/gitlab/build.sh
> +  bash -c 'source /conda/test/bin/activate && /qa/generate_example_models.sh'
Actually I think this is just a matter of `conda-pack` using the older deprecated style of activating conda environments with source activate, just tried it locally: 

```bash
(pytorch-hacking) ➜  pytorch conda-pack
Collecting packages...
Packing environment at '/Users/galahad/mambaforge/envs/pytorch-hacking' to 'pytorch-hacking.tar.gz'
[########################################] | 100% Completed | 15.4s
(base) ➜  pytorch tar -xf pytorch-hacking.tar.gz -C env
(base) ➜  pytorch conda activate env/
(/Users/galahad/Projects/pytorch/env) ➜  pytorch python
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:24:38)
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>
```

I would probably lean on using `conda activate`

2022-04-04 18:59 UTC, dantegd requested changes
Things look good, just the question of using `conda activate` and pinning the conda-pack version

2022-04-04 18:59 UTC, dantegd commented on ops/Dockerfile
> +RUN gpuci_mamba_retry install -c conda-forge conda-pack
I think pinning conda-pack here (0.7?) could save us some head aches

2022-04-04 22:35 UTC, wphicks commented on ci/gitlab/build.sh
> +  bash -c 'source /conda/test/bin/activate && /qa/generate_example_models.sh'
The problem is that one of the things we're trying to do is eliminate `conda` as a dependency in the steps where we make use of those environments. Would we be okay with leaving this as is until `conda-pack` introduces a new recommended workflow for situations where `conda` is not available?

2022-04-06 01:35 UTC, dantegd approved these changes

2022-04-06 02:39 UTC, merged