Provide end-to-end Triton server build
triton-inference-server/fil_backend pull request #43
Opened 2021-05-12 23:49 UTC by wphicks

2021-05-13 16:19 UTC, drobison00 requested changes
Overall looks good, I think it just needs a couple `apt clean` and `pip cache purge` commands added to the end of some command chains to keep the size down.

2021-05-13 16:19 UTC, drobison00 commented on ops/e2e.Dockerfile
> + && rm -rf /var/lib/apt/lists/*
I think you'll want to run `apt clean` at the end of each command chain, that will delete all cached packages as well.

2021-05-13 16:19 UTC, drobison00 commented on ops/e2e.Dockerfile
> + && rm -rf /var/lib/apt/lists/*
apt clean

2021-05-13 16:19 UTC, drobison00 commented on ops/e2e.Dockerfile
> + && rm -rf /var/lib/apt/lists/*
apt clean

2021-05-13 16:19 UTC, drobison00 commented on ops/e2e.Dockerfile
> + && rm -rf /var/lib/apt/lists/*
apt clean

2021-05-13 16:19 UTC, drobison00 commented on ops/e2e.Dockerfile
> +    pip3 install grpcio-tools grpcio-channelz
Will want to add `pip cache purge` here

2021-05-13 17:01 UTC, wphicks commented
Thanks so much! Updated to add apt and pip cache purging accordingly

2021-05-27 16:21 UTC, aroraakshit approved these changes
Looks good!

2021-06-03 23:38 UTC, GuanLuo approved these changes

2021-06-04 00:08 UTC, merged